export enum PlaceDescription {
    'a dark, damp cave',
    'a narrow, twisted tunnel',
    'a deserted shack',
    'a thick, bushy forest',
    'a crumbled ruin of a castle',
    'a mysterious circle of stones',
    'a quiet little village',
    'an empty-looking house',
    'an abandoned fairyground',
    'a deadly silent cemetery',
    'a lush tropical garden',
    'a shady back alley',
    'a dim little pub',
    'a suspicious tent in the middle of nowhere',
    'a nameless settlement',
    'a questionable area of a town, the name of which you are not sure how to pronouce',
    'a strange, crooked building',
    'an old murky cellar',
    'an odd-looking inn',
    'a meadow bathed in moonlight',
    'an enticing disreputable establishment',
    'an eerie forest clearing',
    'a bizzare hill hut',
    'a queer log cabin',
    'a street with a sinister air to it',
    'a weird, almost waterless waterfall',
    'a forsaken children`s playground',
    'a rusty shed',
    'a decaying woodland',
    'a derelict fortress'
}
