export enum WeaponType {
    'Bow',
    'Sword',
    'Axe',
    'Club',
    'Trident',
    'Dagger',
    'Knife',
    'Mace',
    'Lasoo',
    'Crossbow',
    'Nunchucks',
    'Flail',
    'Slingshot',
    'Blade',
    'Shovel',
    'Hammer',
    'Pitchfork',
    'Shuriken',
    'Cutlass',
    'Pike',
    'Spear',
    'Dragon Claw',
    'Frying Pan',
    'Rabid Monkey',
    'Everlasting Vial of Snake Oil',
    'Sentient Tentacles',
    'Territorial Tomcat',
    'Diamond Earring',
    'Tome of Vogon Poetry',
    'Wand of Recursion',
    'Sonic Screwdriver'
}
